import { computed } from "vue";
import { useStore } from "vuex";

import { executeAction } from "../../utils/vuex.util";
import { TypeThemeEnum } from "../../enums/type-theme.enum";

import {
    PANEL_PHONE_CHAT_BACKGROUND_COLOR,
    PANEL_PHONE_CHAT_BORDER_COLOR,

    PANEL_OVERLAY_BACKGROUND_COLOR,
    PANEL_OVERLAY_PHONE_DATA_BACKGROUND_COLOR,
    PANEL_OVERLAY_CONTACTS_HEADER_BACKGROUND_COLOR,
    PANEL_OVERLAY_CONTACTS_HEADER_ICON_COLOR,

    PANEL_OVERLAY_CONFIG_HEADER_BACKGROUND_COLOR,
    PANEL_OVERLAY_CONFIG_HEADER_ICON_COLOR,
    PANEL_OVERLAY_CONFIG_SUMMARY_PROFILE_DATA_INFO_TITLE_FONT_COLOR,
    PANEL_OVERLAY_CONFIG_SUMMARY_PROFILE_DATA_INFO_MESSAGE_FONT_COLOR,
    PANEL_OVERLAY_CONFIG_OPTIONS_ICON_COLOR,
    PANEL_OVERLAY_CONFIG_OPTIONS_OPTION_BORDER_COLOR,
    PANEL_OVERLAY_CONFIG_OPTIONS_OPTION_FONT_COLOR,
    PANEL_OVERLAY_CONFIG_OPTIONS_HOVER_OPTION_BACKGROUND_COLOR,

    PANEL_MODAL_BACKGROUND_COLOR,
    PANEL_MODAL_HEADER_ICON_COLOR,
    PANEL_MODAL_HEADER_FONT_COLOR,

    PANEL_HEADER_BACKGROUND_COLOR,
    PANEL_HEADER_ICON_COLOR,
    PANEL_HEADER_ICON_SELECT_BACKGROUND_COLOR,

    PANEL_HEADER_INFO_CONTACT_ALIAS_FONT_COLOR,
    PANEL_HEADER_INFO_CONTACT_ON_LINE_FONT_COLOR,

    PANEL_DROPDOWN_MENU_BACKGROUND_COLOR,
    PANEL_DROPDOWN_MENU_ITEM_FONT_COLOR,
    PANEL_DROPDOWN_MENU_ITEM_HOVER_BACKGROUND_COLOR,

    PANEL_SEARCH_CONVERSATIONS_BACKGROUND_COLOR,
    PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_BACKGROUND_COLOR,
    PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_ICON_COLOR,
    PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_FONT_COLOR,

    PANEL_OVERSPREAD_PREVIEW_SUMMARY_CONTENT_OPTIONS_ICON_COLOR,

    PANEL_CONVERSATIONS_BACKGROUND_COLOR,

    PANEL_CONVERSATIONS_UNREAD_BACKGROUND_COLOR,
    PANEL_CONVERSATIONS_UNREAD_BORDER_COLOR,
    PANEL_CONVERSATIONS_UNREAD_TITLE_TEXT_FONT_COLOR,
    PANEL_CONVERSATIONS_UNREAD_BOTTOM_MESSAGE_TEXT_FONT_COLOR,

    PANEL_CONTACT_HOVER_BACKGROUND_COLOR,
    PANEL_CONTACT_AVATAR_BORDER_COLOR,

    PANEL_CONTACT_INFO_BORDER_COLOR,
    PANEL_CONTACT_INFO_DATA_NAME_FONT_COLOR,
    PANEL_CONTACT_INFO_DATA_LAST_MESSAGE_FONT_COLOR,
    PANEL_CONTACT_HOVER_INFO_DATA_NAME_FONT_COLOR,
    PANEL_CONTACT_HOVER_INFO_DATA_LAST_MESSAGE_FONT_COLOR,
    PANEL_CONTACT_HOVER_INFO_DATA_LAST_MESSAGE_ICON_COLOR,
    PANEL_CONTACT_UNREAD_INFO_DATA_DATE_LAST_MESSAGE_FONT_COLOR,
    PANEL_CONTACT_UNREAD_INFO_DATA_COUNT_BACKGROUND_COLOR,

    PANEL_OVERLAY_PHONE_CHAT_BACKGROUND_COLOR,
    PANEL_OVERLAY_INTRO_TITLE_MESSAGE_FONT_COLOR,
    PANEL_OVERLAY_INTRO_MESSAGE_FONT_COLOR,

    PANEL_CONVERSATION_HISTORY_BACKGROUND_COLOR,

    PANEL_BUTTON_BOTTOM_BACKGROUND_COLOR,
    PANEL_BUTTON_BOTTOM_FONT_COLOR,

    PANEL_PREVIEW_MEDIA_BACKGROUND_COLOR,
    PANEL_PREVIEW_MEDIA_HEADER_ICON_COLOR,
    PANEL_PREVIEW_MEDIA_HEADER_FONT_COLOR,
    PANEL_PREVIEW_IMAGE_CONTAINER_MESSAGE_BACKGROUND_COLOR,
    PANEL_PREVIEW_IMAGE_CONTAINER_MESSAGE_TEXT_FONT_COLOR,
    PANEL_PREVIEW_DOCUMENT_CONTAINER_BACKGROUND_COLOR,
    PANEL_PREVIEW_DOCUMENT_CONTAINER_PREVIEW_FONT_COLOR,
    PANEL_PREVIEW_DOCUMENT_CONTAINER_MESSAGE_BACKGROUND_COLOR,
    PANEL_PREVIEW_DOCUMENT_CONTAINER_MESSAGE_TEXT_FONT_COLOR,

    PANEL_MESSAGE_HISTORY_BACKGROUND_COLOR,
    PANEL_MESSAGE_HISTORY_NO_FROM_ME_BACKGROUND_COLOR,
    PANEL_MESSAGE_HISTORY_CONTAINER_MESSAGE_DATE_FONT_COLOR,
    PANEL_MESSAGE_HISTORY_TEXT_FONT_COLOR,

    PANEL_QUOTED_MESSAGE_FROM_ME_BACKGROUND_COLOR,
    PANEL_QUOTED_MESSAGE_NO_FROM_ME_BACKGROUND_COLOR,

    PANEL_QUOTED_CONVERSATION_FONT_COLOR,

    PANEL_AUDIO_MESSAGE_PHONES_BACKGROUND_COLOR,
    PANEL_AUDIO_MESSAGE_PHONES_PROFILE_ICON_FONT_COLOR,
    PANEL_AUDIO_MESSAGE_AUDIO_PLAYER_OPTION_ICON_COLOR,
    PANEL_AUDIO_MESSAGE_AUDIO_PLAYER_SEEK_DURATION_FONT_COLOR,

    PANEL_DOCUMENT_MESSAGE_FROM_ME_BACKGROUND_COLOR,
    PANEL_DOCUMENT_MESSAGE_NO_FROM_ME_BACKGROUND_COLOR,
    PANEL_DOCUMENT_MESSAGE_ICON_COLOR,
    PANEL_DOCUMENT_MESSAGE_DESCRIPTION_NAME_FONT_COLOR,
    PANEL_DOCUMENT_MESSAGE_DESCRIPTION_FEATURES_FONT_COLOR,
    PANEL_DOCUMENT_TEXT_MESSAGE_FONT_COLOR,

    PANEL_EMOJIS_BACKGROUND_COLOR,

    PANEL_CATEGORIES_EMOJIS_ICON_COLOR,
    PANEL_CATEGORIES_EMOJIS_CATEGORY_SELECT_ICON_COLOR,
    PANEL_CATEGORIES_EMOJIS_CATEGORY_SELECT_BORDER_COLOR,
    PANEL_CATEGORIES_EMOJIS_TITLE_CATEGORY_FONT_COLOR,

    PANEL_FOOTER_BACKGROUND_COLOR,
    PANEL_FOOTER_ICON_COLOR,
    PANEL_FOOTER_ICON_SELECT_BACKGROUND_COLOR,
    PANEL_FOOTER_MESSAGE_MULTIMEDIA_BACKGROUND_COLOR,
    PANEL_FOOTER_MESSAGE_MULTIMEDIA_FONT_COLOR,

    SCROLL_BACKGROUND_COLOR,

    V_BUTTON_PRIMARY_FONT_COLOR,
    V_BUTTON_PRIMARY_BACKGROUND_COLOR,
    V_BUTTON_PRIMARY_BORDER_COLOR,
    V_BUTTON_SECONDARY_BACKGROUND_COLOR,
    V_BUTTON_SECONDARY_BORDER_COLOR,
    V_BUTTON_SECONDARY_FONT_COLOR,

    V_RADIO_DEFAULT_FONT_COLOR
} from "../../constants/color.constant";

import {
    THEME_STORE_GET_TYPE,
    THEME_STORE_SET_TYPE
} from "../../store/common/theme.store";

let root: any = document.querySelector(':root');

export default function useTheme() {

    const store = useStore();

    const type = computed(
        () => store.getters[THEME_STORE_GET_TYPE]
    );

    const setType = (type: number) => {
        executeAction(THEME_STORE_SET_TYPE, type);
        changeColors(type);
    }

    return {
        type,
        changeColors,
        setType
    }
}

const changeProperty = (property: string, value: string) => {
    root?.style.setProperty(property, value);
}

const changeColors = (type: number) => {
    if (type === TypeThemeEnum.NORMAL) {

        changeProperty(PANEL_PHONE_CHAT_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_PHONE_CHAT_BORDER_COLOR, '#ffffff');

        changeProperty(PANEL_OVERLAY_BACKGROUND_COLOR, 'hsla(0,0%,100%,0.85)');
        changeProperty(PANEL_OVERLAY_PHONE_DATA_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_OVERLAY_CONTACTS_HEADER_BACKGROUND_COLOR, '#008069');
        changeProperty(PANEL_OVERLAY_CONTACTS_HEADER_ICON_COLOR, '#ffffff');

        changeProperty(PANEL_OVERLAY_CONFIG_HEADER_BACKGROUND_COLOR, '#008069');
        changeProperty(PANEL_OVERLAY_CONFIG_HEADER_ICON_COLOR, '#ffffff');
        changeProperty(PANEL_OVERLAY_CONFIG_SUMMARY_PROFILE_DATA_INFO_TITLE_FONT_COLOR, '#111B21');
        changeProperty(PANEL_OVERLAY_CONFIG_SUMMARY_PROFILE_DATA_INFO_MESSAGE_FONT_COLOR, '#666781');
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_ICON_COLOR, '#8696a0');
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_OPTION_BORDER_COLOR, '#f5f6f6');
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_OPTION_FONT_COLOR, '#111b21');
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_HOVER_OPTION_BACKGROUND_COLOR, '#f5f6f6');

        changeProperty(PANEL_MODAL_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_MODAL_HEADER_ICON_COLOR, '#3b4a54');
        changeProperty(PANEL_MODAL_HEADER_FONT_COLOR, '#008069');

        changeProperty(PANEL_OVERSPREAD_PREVIEW_SUMMARY_CONTENT_OPTIONS_ICON_COLOR, '#54656f');

        changeProperty(PANEL_HEADER_BACKGROUND_COLOR, '#f0f2f5');
        changeProperty(PANEL_HEADER_ICON_COLOR, '#54656f');
        changeProperty(PANEL_HEADER_ICON_SELECT_BACKGROUND_COLOR, '#d1d7db');

        changeProperty(PANEL_HEADER_INFO_CONTACT_ALIAS_FONT_COLOR, '#111B21');
        changeProperty(PANEL_HEADER_INFO_CONTACT_ON_LINE_FONT_COLOR, '#667781');

        changeProperty(PANEL_DROPDOWN_MENU_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_DROPDOWN_MENU_ITEM_FONT_COLOR, '#3b4a54');
        changeProperty(PANEL_DROPDOWN_MENU_ITEM_HOVER_BACKGROUND_COLOR, '#f0f2f5');
        
        changeProperty(PANEL_SEARCH_CONVERSATIONS_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_BACKGROUND_COLOR, '#f0f2f5');
        changeProperty(PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_ICON_COLOR, '#00a884');
        changeProperty(PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_FONT_COLOR, '#3b4a54');        

        changeProperty(PANEL_CONVERSATIONS_BACKGROUND_COLOR, '#ffffff');

        changeProperty(PANEL_CONVERSATIONS_UNREAD_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_CONVERSATIONS_UNREAD_BORDER_COLOR, '#e9edef');
        changeProperty(PANEL_CONVERSATIONS_UNREAD_TITLE_TEXT_FONT_COLOR, '#008069');
        changeProperty(PANEL_CONVERSATIONS_UNREAD_BOTTOM_MESSAGE_TEXT_FONT_COLOR, '#3b4a54');

        changeProperty(PANEL_CONTACT_HOVER_BACKGROUND_COLOR, '#f5f6f6');
        changeProperty(PANEL_CONTACT_AVATAR_BORDER_COLOR, '#e9edef');

        changeProperty(PANEL_CONTACT_INFO_BORDER_COLOR, '#e9edef');
        changeProperty(PANEL_CONTACT_INFO_DATA_NAME_FONT_COLOR, '#111B21');
        changeProperty(PANEL_CONTACT_INFO_DATA_LAST_MESSAGE_FONT_COLOR, '#666781');
        changeProperty(PANEL_CONTACT_HOVER_INFO_DATA_NAME_FONT_COLOR, '#111B21');
        changeProperty(PANEL_CONTACT_HOVER_INFO_DATA_LAST_MESSAGE_FONT_COLOR, '#666781');
        changeProperty(PANEL_CONTACT_HOVER_INFO_DATA_LAST_MESSAGE_ICON_COLOR, 'rgba(0,0,0,.4)');
        changeProperty(PANEL_CONTACT_UNREAD_INFO_DATA_DATE_LAST_MESSAGE_FONT_COLOR, '#1fa855');
        changeProperty(PANEL_CONTACT_UNREAD_INFO_DATA_COUNT_BACKGROUND_COLOR, '#25d366');

        changeProperty(PANEL_OVERLAY_PHONE_CHAT_BACKGROUND_COLOR, '#f0f2f5');
        changeProperty(PANEL_OVERLAY_INTRO_TITLE_MESSAGE_FONT_COLOR, '#41525D');
        changeProperty(PANEL_OVERLAY_INTRO_MESSAGE_FONT_COLOR, '#667781');

        changeProperty(PANEL_CONVERSATION_HISTORY_BACKGROUND_COLOR, '#efeae2');

        changeProperty(PANEL_BUTTON_BOTTOM_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_BUTTON_BOTTOM_FONT_COLOR, '#888D90');

        changeProperty(PANEL_PREVIEW_MEDIA_BACKGROUND_COLOR, '#e9edef');
        changeProperty(PANEL_PREVIEW_MEDIA_HEADER_ICON_COLOR, '#54656f');
        changeProperty(PANEL_PREVIEW_MEDIA_HEADER_FONT_COLOR, '#111b21');
        changeProperty(PANEL_PREVIEW_IMAGE_CONTAINER_MESSAGE_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_PREVIEW_IMAGE_CONTAINER_MESSAGE_TEXT_FONT_COLOR, '#3b4a54');
        changeProperty(PANEL_PREVIEW_DOCUMENT_CONTAINER_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_PREVIEW_DOCUMENT_CONTAINER_PREVIEW_FONT_COLOR, '#aebac1');
        changeProperty(PANEL_PREVIEW_DOCUMENT_CONTAINER_MESSAGE_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_PREVIEW_DOCUMENT_CONTAINER_MESSAGE_TEXT_FONT_COLOR, '#3b4a54');

        changeProperty(PANEL_MESSAGE_HISTORY_BACKGROUND_COLOR, '#dcf8c6');
        changeProperty(PANEL_MESSAGE_HISTORY_NO_FROM_ME_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_MESSAGE_HISTORY_CONTAINER_MESSAGE_DATE_FONT_COLOR, '#667781');
        changeProperty(PANEL_MESSAGE_HISTORY_TEXT_FONT_COLOR, '#111b21');

        changeProperty(PANEL_QUOTED_MESSAGE_FROM_ME_BACKGROUND_COLOR, '#d1f4cc');
        changeProperty(PANEL_QUOTED_MESSAGE_NO_FROM_ME_BACKGROUND_COLOR, '#f5f6f6');

        changeProperty(PANEL_QUOTED_CONVERSATION_FONT_COLOR, '#667781');

        changeProperty(PANEL_AUDIO_MESSAGE_PHONES_BACKGROUND_COLOR, 'orange');
        changeProperty(PANEL_AUDIO_MESSAGE_PHONES_PROFILE_ICON_FONT_COLOR, '#6F8171');
        changeProperty(PANEL_AUDIO_MESSAGE_AUDIO_PLAYER_OPTION_ICON_COLOR, '#6f8171');
        changeProperty(PANEL_AUDIO_MESSAGE_AUDIO_PLAYER_SEEK_DURATION_FONT_COLOR, '#8696a0');

        changeProperty(PANEL_DOCUMENT_MESSAGE_FROM_ME_BACKGROUND_COLOR, '#d1f4cc');
        changeProperty(PANEL_DOCUMENT_MESSAGE_NO_FROM_ME_BACKGROUND_COLOR, '#f5f6f6');
        changeProperty(PANEL_DOCUMENT_MESSAGE_ICON_COLOR, '80,101,111');
        changeProperty(PANEL_DOCUMENT_MESSAGE_DESCRIPTION_NAME_FONT_COLOR, '#111B21');
        changeProperty(PANEL_DOCUMENT_MESSAGE_DESCRIPTION_FEATURES_FONT_COLOR, '#8696A0');
        changeProperty(PANEL_DOCUMENT_TEXT_MESSAGE_FONT_COLOR, '#111B21');

        changeProperty(PANEL_EMOJIS_BACKGROUND_COLOR, '#f0f2f5');

        changeProperty(PANEL_CATEGORIES_EMOJIS_ICON_COLOR, 'rgba(17,37,23,.22)');
        changeProperty(PANEL_CATEGORIES_EMOJIS_CATEGORY_SELECT_ICON_COLOR, 'rgba(17,37,23,.42)');
        changeProperty(PANEL_CATEGORIES_EMOJIS_CATEGORY_SELECT_BORDER_COLOR, '#008069');
        changeProperty(PANEL_CATEGORIES_EMOJIS_TITLE_CATEGORY_FONT_COLOR, '#8696A0');

        changeProperty(PANEL_FOOTER_BACKGROUND_COLOR, '#f0f2f5');
        changeProperty(PANEL_FOOTER_ICON_COLOR, '#54656f');
        changeProperty(PANEL_FOOTER_ICON_SELECT_BACKGROUND_COLOR, '#d1d7db');
        changeProperty(PANEL_FOOTER_MESSAGE_MULTIMEDIA_BACKGROUND_COLOR, '#ffffff');
        changeProperty(PANEL_FOOTER_MESSAGE_MULTIMEDIA_FONT_COLOR, '#3b4a54');

        changeProperty(SCROLL_BACKGROUND_COLOR, 'rgba(0,0,0,.2)');

        changeProperty(V_BUTTON_PRIMARY_BACKGROUND_COLOR, '#008069');
        changeProperty(V_BUTTON_PRIMARY_BORDER_COLOR, '#008069');
        changeProperty(V_BUTTON_PRIMARY_FONT_COLOR, '#ffffff');       
        changeProperty(V_BUTTON_SECONDARY_BACKGROUND_COLOR, 'transparent');
        changeProperty(V_BUTTON_SECONDARY_BORDER_COLOR, '#e9edef');
        changeProperty(V_BUTTON_SECONDARY_FONT_COLOR, '#008069');        

        changeProperty(V_RADIO_DEFAULT_FONT_COLOR, '#3b4a54');

    } else if (type === TypeThemeEnum.DARK) {

        changeProperty(PANEL_PHONE_CHAT_BACKGROUND_COLOR, '#222e35');
        changeProperty(PANEL_PHONE_CHAT_BORDER_COLOR, 'rgba(134,150,160,0.15)');

        changeProperty(PANEL_OVERLAY_BACKGROUND_COLOR, 'rgba(0,0,0, 0.8)');
        changeProperty(PANEL_OVERLAY_PHONE_DATA_BACKGROUND_COLOR, '#111b21');
        changeProperty(PANEL_OVERLAY_CONTACTS_HEADER_BACKGROUND_COLOR, '#202c33');
        changeProperty(PANEL_OVERLAY_CONTACTS_HEADER_ICON_COLOR, '#ffffff');

        changeProperty(PANEL_OVERLAY_CONFIG_HEADER_BACKGROUND_COLOR, '#202c33');
        changeProperty(PANEL_OVERLAY_CONFIG_HEADER_ICON_COLOR, '#ffffff');
        changeProperty(PANEL_OVERLAY_CONFIG_SUMMARY_PROFILE_DATA_INFO_TITLE_FONT_COLOR, '#e9edef');
        changeProperty(PANEL_OVERLAY_CONFIG_SUMMARY_PROFILE_DATA_INFO_MESSAGE_FONT_COLOR, '#8696a0');
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_ICON_COLOR, '#8696a0');
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_OPTION_BORDER_COLOR, 'rgba(134,150,160,0.15)');
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_OPTION_FONT_COLOR, '#e9edef');
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_HOVER_OPTION_BACKGROUND_COLOR, '#202c33');

        changeProperty(PANEL_MODAL_BACKGROUND_COLOR, '#3b4a54');
        changeProperty(PANEL_MODAL_HEADER_ICON_COLOR, '#d1d7db');
        changeProperty(PANEL_MODAL_HEADER_FONT_COLOR, '#d1d7db');

        changeProperty(PANEL_OVERSPREAD_PREVIEW_SUMMARY_CONTENT_OPTIONS_ICON_COLOR, '#54656f');

        changeProperty(PANEL_HEADER_BACKGROUND_COLOR, '#202c33');
        changeProperty(PANEL_HEADER_ICON_COLOR, '#aebac1');
        changeProperty(PANEL_HEADER_ICON_SELECT_BACKGROUND_COLOR, '#2a3942');

        changeProperty(PANEL_HEADER_INFO_CONTACT_ALIAS_FONT_COLOR, '#e9edef');
        changeProperty(PANEL_HEADER_INFO_CONTACT_ON_LINE_FONT_COLOR, '#8696a0');

        changeProperty(PANEL_DROPDOWN_MENU_BACKGROUND_COLOR, '#233138');
        changeProperty(PANEL_DROPDOWN_MENU_ITEM_FONT_COLOR, '#d1d7db');
        changeProperty(PANEL_DROPDOWN_MENU_ITEM_HOVER_BACKGROUND_COLOR, '#111b21');
        
        changeProperty(PANEL_SEARCH_CONVERSATIONS_BACKGROUND_COLOR, '#111b21');
        changeProperty(PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_BACKGROUND_COLOR, '#202c33');
        changeProperty(PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_ICON_COLOR, '#00a884');
        changeProperty(PANEL_SEARCH_CONVERSATIONS_SEARCH_TEXT_FONT_COLOR, '#d1d7db');

        changeProperty(PANEL_CONVERSATIONS_BACKGROUND_COLOR, '#111b21');

        changeProperty(PANEL_CONVERSATIONS_UNREAD_BACKGROUND_COLOR, '#111b21');
        changeProperty(PANEL_CONVERSATIONS_UNREAD_BORDER_COLOR, 'rgba(134,150,160,0.15)');
        changeProperty(PANEL_CONVERSATIONS_UNREAD_TITLE_TEXT_FONT_COLOR, '#008069');
        changeProperty(PANEL_CONVERSATIONS_UNREAD_BOTTOM_MESSAGE_TEXT_FONT_COLOR, '#d1d7db');

        changeProperty(PANEL_CONTACT_HOVER_BACKGROUND_COLOR, '#2a3942');
        changeProperty(PANEL_CONTACT_AVATAR_BORDER_COLOR, 'transparent');

        changeProperty(PANEL_CONTACT_INFO_BORDER_COLOR, 'rgba(134,150,160,0.15)');
        changeProperty(PANEL_CONTACT_INFO_DATA_NAME_FONT_COLOR, '#e9edef');
        changeProperty(PANEL_CONTACT_INFO_DATA_LAST_MESSAGE_FONT_COLOR, '#8696a0');
        changeProperty(PANEL_CONTACT_HOVER_INFO_DATA_NAME_FONT_COLOR, '#e9edef');
        changeProperty(PANEL_CONTACT_HOVER_INFO_DATA_LAST_MESSAGE_FONT_COLOR, '#d1d7db');
        changeProperty(PANEL_CONTACT_HOVER_INFO_DATA_LAST_MESSAGE_ICON_COLOR, '#8696a0');
        changeProperty(PANEL_CONTACT_UNREAD_INFO_DATA_DATE_LAST_MESSAGE_FONT_COLOR, '#00a884');
        changeProperty(PANEL_CONTACT_UNREAD_INFO_DATA_COUNT_BACKGROUND_COLOR, '#00a884');

        changeProperty(PANEL_OVERLAY_PHONE_CHAT_BACKGROUND_COLOR, '#222e35');
        changeProperty(PANEL_OVERLAY_INTRO_TITLE_MESSAGE_FONT_COLOR, '#e9edefe0');
        changeProperty(PANEL_OVERLAY_INTRO_MESSAGE_FONT_COLOR, '#8696a0');

        changeProperty(PANEL_CONVERSATION_HISTORY_BACKGROUND_COLOR, '#0b141a');

        changeProperty(PANEL_BUTTON_BOTTOM_BACKGROUND_COLOR, '#202C33');
        changeProperty(PANEL_BUTTON_BOTTOM_FONT_COLOR, '#798287');

        changeProperty(PANEL_PREVIEW_MEDIA_BACKGROUND_COLOR, '#101a20');
        changeProperty(PANEL_PREVIEW_MEDIA_HEADER_ICON_COLOR, '#aebac1');
        changeProperty(PANEL_PREVIEW_MEDIA_HEADER_FONT_COLOR, '#e9edef');
        changeProperty(PANEL_PREVIEW_IMAGE_CONTAINER_MESSAGE_BACKGROUND_COLOR, '#2b3b45');
        changeProperty(PANEL_PREVIEW_IMAGE_CONTAINER_MESSAGE_TEXT_FONT_COLOR, '#d1d7db');
        changeProperty(PANEL_PREVIEW_DOCUMENT_CONTAINER_BACKGROUND_COLOR, '#101a20');
        changeProperty(PANEL_PREVIEW_DOCUMENT_CONTAINER_PREVIEW_FONT_COLOR, '#aebac1');
        changeProperty(PANEL_PREVIEW_DOCUMENT_CONTAINER_MESSAGE_BACKGROUND_COLOR, '#2b3b45');
        changeProperty(PANEL_PREVIEW_DOCUMENT_CONTAINER_MESSAGE_TEXT_FONT_COLOR, '#d1d7db');

        changeProperty(PANEL_MESSAGE_HISTORY_BACKGROUND_COLOR, '#005c4b');
        changeProperty(PANEL_MESSAGE_HISTORY_NO_FROM_ME_BACKGROUND_COLOR, '#202c33');
        changeProperty(PANEL_MESSAGE_HISTORY_CONTAINER_MESSAGE_DATE_FONT_COLOR, '#ffffff99');
        changeProperty(PANEL_MESSAGE_HISTORY_TEXT_FONT_COLOR, '#e9edef');

        changeProperty(PANEL_QUOTED_MESSAGE_FROM_ME_BACKGROUND_COLOR, '#025144');
        changeProperty(PANEL_QUOTED_MESSAGE_NO_FROM_ME_BACKGROUND_COLOR, '#1d282f');

        changeProperty(PANEL_QUOTED_CONVERSATION_FONT_COLOR, '#FFFFFF99');

        changeProperty(PANEL_AUDIO_MESSAGE_PHONES_BACKGROUND_COLOR, 'orange');
        changeProperty(PANEL_AUDIO_MESSAGE_PHONES_PROFILE_ICON_FONT_COLOR, '#e9edef');
        changeProperty(PANEL_AUDIO_MESSAGE_AUDIO_PLAYER_OPTION_ICON_COLOR, '#d1d7db');
        changeProperty(PANEL_AUDIO_MESSAGE_AUDIO_PLAYER_SEEK_DURATION_FONT_COLOR, '#ffffff99');

        changeProperty(PANEL_DOCUMENT_MESSAGE_FROM_ME_BACKGROUND_COLOR, '#025144');
        changeProperty(PANEL_DOCUMENT_MESSAGE_NO_FROM_ME_BACKGROUND_COLOR, '#1d282f');
        changeProperty(PANEL_DOCUMENT_MESSAGE_ICON_COLOR, '174,186,193');
        changeProperty(PANEL_DOCUMENT_MESSAGE_DESCRIPTION_NAME_FONT_COLOR, '#E9EDEF');
        changeProperty(PANEL_DOCUMENT_MESSAGE_DESCRIPTION_FEATURES_FONT_COLOR, '#FFFFFF99');
        changeProperty(PANEL_DOCUMENT_TEXT_MESSAGE_FONT_COLOR, '#E9EDEF');

        changeProperty(PANEL_EMOJIS_BACKGROUND_COLOR, '#202c33');

        changeProperty(PANEL_CATEGORIES_EMOJIS_ICON_COLOR, 'rgba(233,237,239,.32)');
        changeProperty(PANEL_CATEGORIES_EMOJIS_CATEGORY_SELECT_ICON_COLOR, '#8696a0');
        changeProperty(PANEL_CATEGORIES_EMOJIS_CATEGORY_SELECT_BORDER_COLOR, '#00a884');
        changeProperty(PANEL_CATEGORIES_EMOJIS_TITLE_CATEGORY_FONT_COLOR, '#667781');

        changeProperty(PANEL_FOOTER_BACKGROUND_COLOR, '#202c33');
        changeProperty(PANEL_FOOTER_ICON_COLOR, '#8696a0');
        changeProperty(PANEL_FOOTER_ICON_SELECT_BACKGROUND_COLOR, '#2a3942');
        changeProperty(PANEL_FOOTER_MESSAGE_MULTIMEDIA_BACKGROUND_COLOR, '#2a3942');
        changeProperty(PANEL_FOOTER_MESSAGE_MULTIMEDIA_FONT_COLOR, '#d1d7db');

        changeProperty(SCROLL_BACKGROUND_COLOR, 'rgba(255,255,255,0.1)');
        
        changeProperty(V_BUTTON_PRIMARY_BACKGROUND_COLOR, '#00a884');
        changeProperty(V_BUTTON_PRIMARY_BORDER_COLOR, '#00a884');
        changeProperty(V_BUTTON_PRIMARY_FONT_COLOR, '#111b21');
        changeProperty(V_BUTTON_SECONDARY_BACKGROUND_COLOR, 'transparent');
        changeProperty(V_BUTTON_SECONDARY_BORDER_COLOR, 'rgba(134,150,160,0.15)');
        changeProperty(V_BUTTON_SECONDARY_FONT_COLOR, '#00a884');        

        changeProperty(V_RADIO_DEFAULT_FONT_COLOR, '#d1d7db');

    } else if (type === TypeThemeEnum.BLUE) {

    } else if (type === TypeThemeEnum.ORANGE) {

    } else if (type === TypeThemeEnum.PURPLE) {
        changeProperty(PANEL_HEADER_BACKGROUND_COLOR, '#7F1974');
        changeProperty(PANEL_HEADER_ICON_COLOR, '#fff');
        changeProperty(PANEL_HEADER_INFO_CONTACT_ALIAS_FONT_COLOR, '#ffffff');
        changeProperty(PANEL_HEADER_INFO_CONTACT_ON_LINE_FONT_COLOR, '#ffffff')

        changeProperty(PANEL_OVERLAY_CONTACTS_HEADER_BACKGROUND_COLOR, "#7F1974");
        changeProperty(PANEL_OVERLAY_CONFIG_HEADER_BACKGROUND_COLOR, "#7F1974");
        changeProperty(PANEL_OVERLAY_CONFIG_OPTIONS_ICON_COLOR, "#7F1974");

        changeProperty(PANEL_MODAL_HEADER_ICON_COLOR, "#7F1974");

        changeProperty(PANEL_FOOTER_BACKGROUND_COLOR, '#f0f2f5');
        changeProperty(PANEL_FOOTER_ICON_COLOR, '#54656f');

        changeProperty(V_BUTTON_PRIMARY_BACKGROUND_COLOR, "#7F1974");
        changeProperty(V_BUTTON_PRIMARY_BORDER_COLOR, "#7F1974");
        changeProperty(V_BUTTON_SECONDARY_BORDER_COLOR, '#7F1974');
        changeProperty(V_BUTTON_SECONDARY_FONT_COLOR, '#7F1974');

        changeProperty(SCROLL_BACKGROUND_COLOR, '#7F1974');
    }
}